/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pfilaretov42_java22_ffm_api_ElvenScrollBefore */

#ifndef _Included_dev_pfilaretov42_java22_ffm_api_ElvenScrollBefore
#define _Included_dev_pfilaretov42_java22_ffm_api_ElvenScrollBefore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pfilaretov42_java22_ffm_api_ElvenScrollBefore
 * Method:    countRunes
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dev_pfilaretov42_java22_ffm_1api_ElvenScrollBefore_countRunes
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
